'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import LoadingScreen from '../components/LoadingScreen';

export default function UtilityReportPage() {
  const [reportData, setReportData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchReport = async () => {
      try {
        // Fetch from the static JSON generated by utility_manager.py
        const res = await fetch('/utility_report.json');
        if (!res.ok) {
          throw new Error('Report data not available. Has the daily job run?');
        }
        const data = await res.json();
        setReportData(data);
      } catch (err: any) {
        setError(err.message || 'Failed to load report');
      } finally {
        setLoading(false);
      }
    };
    fetchReport();
  }, []);

  if (loading) return <LoadingScreen label="Loading utility report" />;

  return (
    <main className="min-h-screen bg-[#F9F9F7] text-[#111111] p-4 sm:p-8 font-sans selection:bg-[#111111] selection:text-white">
      <div className="max-w-6xl mx-auto space-y-8">
        
        {/* HEADER */}
        <header className="bg-[#F9F9F7] border-2 border-[#111111] hard-shadow-hover rounded-none p-5 sm:p-8 flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
          <div className="flex items-center gap-4">
            <Link href="/" className="hover:opacity-80 transition-opacity">
              <img src="/logo.png" alt="Prem Industries Logo" className="h-16 w-auto object-contain" />
            </Link>
            <div>
              <h1 className="text-3xl sm:text-4xl font-semibold text-[#111111] tracking-tight">Daily Utility Report</h1>
              <p className="text-[#737373] text-sm mt-1 uppercase tracking-widest">Complex Maintenance Overview</p>
            </div>
          </div>
          <div className="flex flex-col items-end">
            <Link href="/" className="bg-[#111111] text-white hover:bg-white hover:text-[#111111] border-2 border-[#111111] font-medium px-6 py-3 rounded-none transition-colors uppercase tracking-wider text-sm flex items-center gap-2">
              <span>←</span> Return to Dashboard
            </Link>
            {reportData && (
              <p className="text-xs text-[#737373] mt-3">
                Generated: {new Date(reportData.generated_at).toLocaleString()}
              </p>
            )}
          </div>
        </header>

        {error && (
          <div className="bg-red-50 border-2 border-red-500 text-red-700 p-6 rounded-none font-medium text-sm">
            ERROR: {error}
          </div>
        )}

        {reportData && reportData.reports && reportData.reports.length === 0 && (
          <div className="border-2 border-[#111111] bg-white p-12 text-center">
            <p className="text-[#525252] font-medium text-lg">No machines currently require maintenance.</p>
          </div>
        )}

        {/* ALERTS SECTION */}
        {reportData && reportData.reports && reportData.reports.length > 0 && (
          <div className="grid grid-cols-1 gap-6">
            {reportData.reports.map((machine: any) => (
              <div key={machine.machine_id} className="border-2 border-[#111111] bg-white p-0 flex flex-col">
                <div className="bg-[#111111] text-white p-4 flex justify-between items-center">
                  <div>
                    <h2 className="text-xl font-bold">{machine.machine_name}</h2>
                    <p className="text-sm opacity-80 font-mono mt-1">{machine.asset_tag}</p>
                  </div>
                  <div className="text-right">
                    <span className="text-xs uppercase tracking-widest opacity-80">Last Maintained</span>
                    <p className="font-mono">{machine.last_maintenance || 'N/A'}</p>
                  </div>
                </div>
                
                <div className="p-6 divide-y-2 divide-[#111111]/10">
                  {machine.alerts.map((alert: any, idx: number) => (
                    <div key={idx} className="py-4 first:pt-0 last:pb-0">
                      <div className="flex justify-between items-start mb-3">
                        <h3 className="text-lg font-semibold flex items-center gap-2">
                          {alert.alert_level === 3 ? <span className="text-red-600">🚨 DUE FOR</span> : <span className="text-yellow-600">⚠️ UPCOMING</span>}
                          <span>{alert.service_type} Service</span>
                        </h3>
                        <span className={`px-3 py-1 text-xs font-bold uppercase border-2 ${alert.alert_level === 3 ? 'border-red-600 text-red-600' : 'border-[#111111] text-[#111111]'}`}>
                          Level {alert.alert_level}
                        </span>
                      </div>
                      
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
                        <div className={`p-4 border-2 ${alert.hrs_alert_level > 0 ? 'border-[#111111] bg-[#F9F9F7]' : 'border-gray-200 opacity-50'}`}>
                          <p className="text-xs uppercase font-bold tracking-widest text-[#737373] mb-1">Usage Check</p>
                          {alert.interval_hrs ? (
                            <>
                              <p className="text-2xl font-mono">{alert.current_hrs} <span className="text-sm font-sans text-[#737373]">/ {alert.interval_hrs} hrs</span></p>
                              {alert.hrs_alert_level > 0 && <p className="text-sm font-semibold mt-2 text-red-600">Action Required</p>}
                            </>
                          ) : (
                            <p className="text-sm text-[#737373]">Not Monitored</p>
                          )}
                        </div>
                        <div className={`p-4 border-2 ${alert.days_alert_level > 0 ? 'border-[#111111] bg-[#F9F9F7]' : 'border-gray-200 opacity-50'}`}>
                          <p className="text-xs uppercase font-bold tracking-widest text-[#737373] mb-1">Time Check</p>
                          {alert.interval_days ? (
                            <>
                              <p className="text-2xl font-mono">{alert.days_passed !== null ? alert.days_passed : '0'} <span className="text-sm font-sans text-[#737373]">/ {alert.interval_days} days</span></p>
                              {alert.days_alert_level > 0 && <p className="text-sm font-semibold mt-2 text-red-600">Action Required</p>}
                            </>
                          ) : (
                            <p className="text-sm text-[#737373]">Not Monitored</p>
                          )}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        )}

      </div>
    </main>
  );
}
